### PR TITLE
Feature milestone 3

### PR DESCRIPTION
**Pull request by nurislam-ab**
This PR has the following:
- [x] Flexbox to display the calculator
- [x] styles for the display component
- [x] styles for the ButtonPanel component
- [x] styles for the Button component
- [x] passing color and wide props to the Button component

### CODE REVIEW

**Review by MauricioRobayo — CHANGES_REQUESTED** [review]
Nice, well done!

Could you please check the borders:

image

Some buttons seems to be missing borders, some borders are thicker than others, and there is a misalignment in some borders.

Let's make this project shine!

- [ ] Fix button borders to be uniform and aligned.

Other than that, the project is looking great.

Status: **Request changes**.

**OPTIONAL**: There seems to be an ESlint issue on the [linters-config](https://github.com/microverseinc/linters-config/tree/master/react-redux) repo because your project is having a lot of ESLint issues, you can see it by running `npx eslint src/**/*.{js,jsx}` after installing the dependencies listed on the config-linter repo. We will need to check that the configuration provided is working as expected, but you might want to make sure you are following ESLint rules.

**Comment by nurislam-ab** [comment]
I didn't add the left and right borders for the calculator wrapper cause the design doesn't have them ([Screenshot from the requirements](http://joxi.ru/L21g5BoS0RGRWr)).

For this PR I've added them as requested [Screenshot](http://joxi.ru/V2V067OtkdEKEr)

**Comment by nurislam-ab** [comment]
ESLint fails for some reason. Even though the code is not in this branch and PR doesn't have that code also
http://joxi.ru/p27pZYPTNK3PYA

**Review by Torres-ssf — APPROVED** [review]
### Milestone approved :+1: :clap: 
Hi @nurislam-ab :hand: 
**The linter error is clearly a strange bug since it's related to a file that does not exist on this branch**. And since all requirements were met, I'm approving this PR
Good luck with the next one :clap: :tada: 

Happy Coding :computer: 
**Sergio Torres**

**Pull request merged**
